version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/motorcycleshopdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=motorcycleshopdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  flyway:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/motorcycleshopdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    command: [ "mvn", "flyway:migrate" ]
