FROM maven:3.8.4-openjdk-17 as builder
WORKDIR /app
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
COPY ./src ./src
ADD /target/MotorcycleShop-db-test-0.0.1-SNAPSHOT.jar app.jar
RUN mvn dependency:go-offline
RUN mvn clean package -Dmaven.test.skip
CMD ["java", "-jar", "./app.jar"]
