
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db


#  postgres:
#    container_name: postgres-sql
#    image: postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: root
#      POSTGRES_DB: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres:/var/lib/postgres/data
#    networks:
#      - spring-boot-network
#    restart: unless-stopped
#
#  spring-boor-app:
#    container_name: motorcycleshop
#    image: motorcycleshop
#    ports:
#      - "5050:80"
#    networks:
#      - spring-boot-network
#    restart: unless-stopped
#    depends_on:
#      - postgres
#
#networks:
#  spring-boot-network:
#    driver: bridge
#
#volumes:
#  postgres:
